on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@master
      with:
         path: './src/github.com/meterup/github-release'
    # staticcheck needs this for GOPATH
    - run: echo "::set-env name=GOPATH::$GITHUB_WORKSPACE"
    - run: echo "::set-env name=PATH::$GITHUB_WORKSPACE/bin:$PATH"
    - name: Download dependencies
      run: go get -t -v ./...
      working-directory: './src/github.com/meterup/github-release'
    - name: Run tests
      run: make test
      working-directory: './src/github.com/meterup/github-release'
